### ISSUE TITLE
BCF 2.1 file failing to import

### ISSUE THREAD

**Issue by anorrie** [3drepo/3drepo.io#2975]
### Description

BCF files from Solibri are failing to import 

- This is happening in: prod 
- This requires a hotfix to production: yes 

### Steps to replicate
- Import a BCF v2.1 file from Solibri - https://www.dropbox.com/s/o8w4kde6mm9hliw/Test%20Issues_21.bcf?dl=0

### Current Behaviour
- Internal error message as below 

### Expected Behaviour
- BCF should import 

### Pictures/ Gifs of the error
![3D Repo Import BCF 2 1 error](https://user-images.githubusercontent.com/41000373/151135871-235b1ae7-0e7c-48a0-8387-c7ab8289d2f2.JPG)

**Comment by keifgwinn** [comment]
TypeError: Cannot set property 'ViewSetupHints' of undefined
    at /home/node/3drepo.io/backend/src/v4/models/bcf.js:667:30
    at Array.forEach (<anonymous>)
    at parseViewpointComponents (/home/node/3drepo.io/backend/src/v4/models/bcf.js:663:51)
    at readBCF (/home/node/3drepo.io/backend/src/v4/models/bcf.js:956:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Issue.importBCF (/home/node/3drepo.io/backend/src/v4/models/issue.js:180:21) 
    
is the error being generated in prod, on staging this file returns
<img width="333" alt="image" src="https://user-images.githubusercontent.com/23369849/151141656-4f7c557d-cc54-4359-b38d-5b7b6b9ed020.png">
