### ISSUE TITLE
DB connection problem with latest connect-mongodb-session

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#3185]
### Description

The latest version (3.1.1) causes problems when connecting to a remote DB from backend. Here: https://github.com/3drepo/3drepo.io/blob/master/backend/package.json#L34

It works when reverted back to 2.4.1

### Steps to replicate
- Go to `staging` branch
- Run backend with remote DB config
- Try to use local 3drepo

### Current Behaviour
```
$ cross-env NODE_CONFIG_DIR=../config node ./src/v4/3drepo.js
2022-04-27T16:25:58.112Z [info] [APP]     Loading api on 127.0.0.1:8080
2022-04-27T16:25:58.501Z [info] [AMQP]     Connecting to amqp://localhost:5672...
2022-04-27T16:25:58.721Z [info] [APP]     Loading frontend on 127.0.0.1:8080
2022-04-27T16:25:59.042Z [info] [APP]     Loading chat on 127.0.0.1:3000
2022-04-27T16:25:59.044Z [info] [APP]     Starting server on 0.0.0.0 port 3000
2022-04-27T16:25:59.044Z [info] [APP]     Starting server on 0.0.0.0 port 8080
(node:10665) UnhandledPromiseRejectionWarning: Error: Error connecting to db: getaddrinfo EAI_AGAIN dev-mongo-primary
    at /home/charence/Workspace/3drepo.io/backend/node_modules/connect-mongodb-session/index.js:88:17
    at /home/charence/Workspace/3drepo.io/backend/node_modules/connect-mongodb-session/node_modules/mongodb/lib/utils.js:413:17
    at /home/charence/Workspace/3drepo.io/backend/node_modules/connect-mongodb-session/node_modules/mongodb/lib/mongo_client.js:129:28
    at connectCallback (/home/charence/Workspace/3drepo.io/backend/node_modules/connect-mongodb-session/node_modules/mongodb/lib/operations/connect.js:29:9)
    at /home/charence/Workspace/3drepo.io/backend/node_modules/connect-mongodb-session/node_modules/mongodb/lib/operations/connect.js:78:20
    at Object.callback (/home/charence/Workspace/3drepo.io/backend/node_modules/connect-mongodb-session/node_modules/mongodb/lib/sdam/topology.js:208:50)
    at Timeout._onTimeout (/home/charence/Workspace/3drepo.io/backend/node_modules/connect-mongodb-session/node_modules/mongodb/lib/sdam/topology.js:319:33)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10665) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10665) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by carmenfan** [comment]
If we use https://www.npmjs.com/package/connect-mongo instead, then we could use an existing connection to support the session management

This avoids the driver trying to connect themselves, and try to be clever about talking to the replica set when it's not explicitly stated on the URI
