### ISSUE TITLE
New user signups having an exception

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3204]
### Description

New users are trying to sign up and getting an exception to the UI and a server 500 error on the server side. The user account is created, and verifiable to get the account created.

- This is happening in: prod
- This requires a hotfix to production: possibly

### Steps to replicate
- Sign up a new user

### Current Behaviour
- This results

```
[www-588c4b6c87-2srbq] (node:42) [MONGODB DRIVER] Warning: Creating a user without roles is deprecated in MongoDB >= 2.6
[www-588c4b6c87-2srbq] {"label":"NET","level":"error","message":"TypeError: Cannot read property 'customData' of null\n    at Object.invitations.unpack (/home/node/3drepo.io/backend/src/v4/models/invitations.js:228:28)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Object.User.createUser (/home/node/3drepo.io/backend/src/v4/models/user.js:507:2) ","timestamp":"2022-05-05T16:14:00.595Z"}
[www-588c4b6c87-2srbq] {"label":"NET","level":"info","message":"{\"status\":500,\"latency\":\"181\",\"contentLength\":91,\"user\":\"unknown\",\"method\":\"POST\",\"originalUrl\":\"/api/toytest202205054\"} ","timestamp":"2022-05-05T16:14:00.595Z"}
```
### Expected Behaviour
- No errors on creating the user

**Comment by carmenfan** [comment]
N/A - this was a write concern/read concern problem on the DB
